"""add video_source and task_run

Revision ID: e701f2d627d3
Revises: 
Create Date: 2026-07-19 10:24:15.363853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e701f2d627d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='视频源名称'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='local_file/rtsp/rtmp/http'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='视频源地址/路径'),
    sa.Column('media_mtx_path', sa.String(length=100), nullable=True, comment='MediaMTX推流路径'),
    sa.Column('connection_status', sa.String(length=20), nullable=True, comment='unknown/checking/online/offline'),
    sa.Column('last_probe_at', sa.DateTime(), nullable=True, comment='上次探测时间'),
    sa.Column('last_probe_ok', sa.Boolean(), nullable=True, comment='上次探测是否成功'),
    sa.Column('format_name', sa.String(length=50), nullable=True, comment='封装格式'),
    sa.Column('width', sa.Integer(), nullable=True, comment='视频宽度'),
    sa.Column('height', sa.Integer(), nullable=True, comment='视频高度'),
    sa.Column('fps', sa.Float(), nullable=True, comment='帧率'),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='对应任务ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='created/starting/running/stopping/stopped/failed'),
    sa.Column('config_snapshot', sa.JSON(), nullable=False, comment='启动时的配置快照'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('stopped_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True, comment='引用VideoSource'))
        batch_op.create_index(batch_op.f('ix_analysis_tasks_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key(None, 'video_sources', ['source_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_source_id'))
        batch_op.drop_column('source_id')

    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_runs_status'))

    op.drop_table('task_runs')
    op.drop_table('video_sources')
    # ### end Alembic commands ###
